version: "3.5"

services:
  console:
    build:
      context: ./containers/
      dockerfile: ./console/Dockerfile 
    container_name: ${APPNAME:?err}-console
    environment:
      - ENVSET
      - APPNAME
      - HOSTUID
      - HOSTGID
      - NODEVERSION
    volumes:
      - ./storage/app:/storage/app
      - ./storage/database:/storage/database
      - ./storage/certs:/storage/certs
    networks:
      - ${APPNAME:?err}-console
    
  web:
    build:
      context: ./containers/
      dockerfile: ./web/Dockerfile 
    ports:
      - "${BINDHTTP}"
      - "${BINDHTTPS}"
    container_name: ${APPNAME:?err}-web
    environment:
      - APPNAME
      - WILDCARDCERT
      - WWWDOMAIN
      - HTACCESS
      - HTUSER
      - HTPASS
      - ENVSET
      - HOSTUID
      - HOSTGID
      - NODEVERSION
      - DATABASENAME
      - DATABASEUSER
    volumes:
      - ./storage/app:/storage/app
      - ./storage/certs:/storage/certs
      - ./storage/app:/var/www/html
      - ./storage/logs/nginx:/var/log/nginx
    networks:
      - ${APPNAME:?err}-console
    depends_on:
      - console

  redis:
    build:
      context: ./containers/
      dockerfile: ./redis/Dockerfile 
    ports:
      - "${BINDREDIS}"
    container_name: ${APPNAME:?err}-redis
    environment:
      - ENVSET
      - HOSTUID
      - HOSTGID
    networks:
      - ${APPNAME:?err}-console

  db:
    build:
      context: ./containers/
      dockerfile: ./mysql/Dockerfile 
    ports:
      - "${BINDMYSQL}"
    container_name: ${APPNAME:?err}-db
    environment:
      - ENVSET
      - HOSTUID
      - HOSTGID
      - DATABASENAME
      - DATABASEUSER
    volumes:
      - ./storage/database:/mysql
    networks:
      - ${APPNAME:?err}-console
  
  maildev:
    container_name: ${APPNAME:?err}_maildev
    image: maildev/maildev
    ports:
      - "1080:80"
    networks:
      - ${APPNAME:?err}-console


networks:
  ${APPNAME:?err}-console:
