version: "3.5"

services:
  console:
    build:
      context: ./containers/
      dockerfile: ./qdlaravel-console/Dockerfile 
    container_name: qdlaravel-console
    environment:
      - QDLARAVELENVSET
      - HOSTUID
      - HOSTGID
    volumes:
      - ./storage/app:/storage/app
      - ./storage/database:/storage/database
      - ./storage/certs:/storage/certs
    networks:
      qdlaravel-net:

  web:
    build:
      context: ./containers/
      dockerfile: ./qdlaravel-web/Dockerfile 
    ports:
      - ${BINDHTTP}
      - ${BINDHTTPS}
    container_name: qdlaravel-web
    environment:
      - WWWDOMAIN:"www.qdlaravel.local"
      - QDLARAVELENVSET
      - HOSTUID
      - HOSTGID
    volumes:
      - ./storage/app:/storage/app
      - ./storage/certs:/storage/certs
      - ./storage/app:/var/www/html
    networks:
      qdlaravel-net:

  redis:
    build:
      context: ./containers/
      dockerfile: ./qdlaravel-redis/Dockerfile 
    ports:
      - ${BINDREDIS}
    container_name: qdlaravel-redis
    environment:
      - QDLARAVELENVSET
      - HOSTUID
      - HOSTGID
    networks:
      qdlaravel-net:        

  db:
    build:
      context: ./containers/
      dockerfile: ./qdlaravel-mysql/Dockerfile 
    ports:
      - ${BINDMYSQL}
    container_name: qdlaravel-db
    environment:
      - QDLARAVELENVSET
      - HOSTUID
      - HOSTGID
    volumes:
      - ./storage/database:/mysql
    networks:
      qdlaravel-net:
      
networks:
  qdlaravel-net: