#!/bin/bash -x

#Pull in functions 
source /root/bash-functions.sh

export DEBIAN_FRONTEND=noninteractive

#We trash the cache data in configure_99_cleanup
evalcommand "apt update" 1

#Install 
evalcommand "apt install -y nginx php-fpm php-cli php-mysql php-bcmath php-json php-mbstring php-services-json php-tokenizer php-xml" 1

PHPVER=$( apt list | egrep "^php[0-9]\.[0-9]\/" | sed -r 's/php([0-9]{1}\.[0-9]{1}).*/\1/g' )
echo "${PHPVER}" > /root/php-version

#Enable short tags
sed -r -i 's/(short_open_tag\s?=\s?Off)/#Was \1\nshort_open_tag = on/i' /etc/php/*/*/php.ini

#Install dependencies
evalcommand "apt install -y git curl unzip apache2-utils" 1
#apache utils required for htpasswd

#Set path for future use
echo 'export PATH="$PATH:$HOME/.config/composer/vendor/bin"' | tee -a /root/.bashrc

#evalcommand "apt purge -y curl" 1
exit 0
